export const siteConfig = {
  name: "Josuan Leonardo Hulom",
  shortName: "Josuan",
  title:
    "Josuan | Full-Stack Developer | Back-End, Server Architecture & Mobile Skills",
  description:
    "Portfolio of Josuan Leonardo Hulom — a Full-Stack Developer in Cebu, Philippines with strong back-end and server architecture skills, mobile development skills, and web development skills. Explore technical skills in React.js, Python, Flutter, PostgreSQL, and full-stack project experience.",
  url: "https://josuan.cv",
  locale: "en_US",
  email: "hulomjosuan@gmail.com",
  phone: "+639682006456",
  location: "Tabogon, Cebu, Philippines",
  linkedIn: "https://www.linkedin.com/in/hulomjosuan/",
  github: "https://github.com/hulomjosuan21",
  role: "Full-Stack Developer",
  specialization:
    "Back-End & Server Architecture with mobile and web development skills",
  keywords: [
    "full-stack developer skills",
    "back-end developer skills",
    "server architecture skills",
    "mobile development skills",
    "web development skills",
    "React.js skills",
    "Python developer skills",
    "Flutter developer skills",
    "PostgreSQL skills",
    "TypeScript skills",
    "Next.js skills",
    "software developer Philippines",
    "Cebu developer",
    "Josuan Leonardo Hulom",
    "full-stack developer portfolio",
    "technical skills",
    "programming skills",
    "API development skills",
    "database skills",
    "POS system developer",
    "inventory system developer",
  ],
  skills: [
    "Back-End Development",
    "Server Architecture",
    "Mobile Development",
    "Web Development",
    "React.js",
    "Next.js",
    "Python",
    "FastAPI",
    "Flutter",
    "Dart",
    "TypeScript",
    "JavaScript",
    "PostgreSQL",
    "MongoDB",
    "Supabase",
    "Docker",
    "REST API Design",
    "ORM Workflows",
    "Full-Stack Development",
  ],
} as const;
